package com.byd.clusternav.launcher

import com.byd.clusternav.testsupport.SourceRoots
import java.nio.file.Files
import java.nio.file.Path
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * ═══ U9 · "MỘT CHIẾC XE" — bảng lớn, icon 24dp và SVG nguồn phải là CÙNG một chuỗi path ═══════════════════════════
 *
 * Spec `docs/specs/kachi-car-boards.html` §3 R1/R5 · **VISUAL-REFRESH P3** `kachi-visual-refresh.html` R1
 * (AC1.1 ba tệp SVG · AC1.2 so từng ký tự SVG ↔ pathData ↔ Kotlin · AC1.3 mọi hằng có chỗ gọi · AC1.4 bốn bảng không
 * tự vẽ thân · AC1.6 tầng vẽ đi qua `CarArtSource`).
 *
 * ## Ba bất biến được khoá
 *  1. **Không tự vẽ nữa** — ba bảng Canvas không còn `drawRoundRect(body…)`/`drawLine(`; `CarMiniView` (chiếc xe
 *     THỨ BA mà spec bỏ sót, B2 tìm ra) **0** `drawRoundRect`; cả ba vẽ qua [CarArtPainter].
 *  2. **Chuỗi path là bản SINH** — `CarFrames.kt` giữ **0** literal; mọi chuỗi ở `CarFramesGenerated.kt` xuất hiện
 *     **từng ký tự** trong `res/drawable/ic_car_*.xml` hoặc `car_face_*.xml` (đường ống một nguồn hai đích), và
 *     ngược lại mọi `android:pathData` của `ic_car_*` là một chuỗi mảnh hoặc chuỗi NỐI của các mảnh (icon gộp nhiều
 *     mảnh bằng một dấu cách). SVG nguồn ↔ tệp sinh do `gen-car.py --check` khoá byte (`IconStyleContractTest`).
 *  3. **Phóng GIỮ TỈ LỆ** — `ScaleToFit.CENTER`, và chỗ duy nhất dựng ma trận phóng là [CarFrames.fit].
 */
class CarFramesSourceContractTest {

    private val frames by lazy { code("src/main/java/com/byd/clusternav/launcher/CarFrames.kt") }
    private val generated by lazy { code("src/main/java/com/byd/clusternav/launcher/CarFramesGenerated.kt") }

    /** Ba bảng Canvas vẽ hình xe — toàn bộ chỗ từng (hoặc có thể) tự vẽ thân xe. */
    private val boardFiles = listOf("TyreBoardView.kt", "DoorBoardView.kt", "CarMiniView.kt")

    private fun code(relative: String): String = SourceRoots.codeOf(relative)
    private fun boardCode(name: String): String = code("src/main/java/com/byd/clusternav/launcher/$name")
    private fun drawableDir(): Path = SourceRoots.path("src/main/res/drawable")

    private fun pathData(file: String): List<String> =
        PATH_DATA.findAll(drawableDir().resolve(file).toFile().readText()).map { it.groupValues[1] }.toList()

    /** `ic_car_` = ba mặt `top_/front_/rear_` (KHÔNG phải glyph `ic_car`/`ic_car_l`/`ic_car_xl` của lĩnh vực Danh tính). */
    private fun carFiles(prefix: String): List<String> = Files.list(drawableDir()).use { s ->
        s.map { it.fileName.toString() }.filter { n ->
            n.endsWith(".xml") && if (prefix == "ic_car_") listOf("ic_car_top_", "ic_car_front_", "ic_car_rear_").any { n.startsWith(it) } else n.startsWith(prefix)
        }.toList()
    }

    /** Mọi chuỗi path SINH (hằng `Piece(…, "M…", …)`). */
    private fun generatedPaths(): List<String> = LITERAL.findAll(generated).map { it.groupValues[1] }.toList()

    // ── 1 · ba bảng không còn tự vẽ thân xe, và vẽ qua CarArtSource ────────────────────────────────────────

    @Test
    fun `ba bang khong con tu ve than xe ma di qua CarArtPainter`() {
        boardFiles.forEach { name ->
            val src = boardCode(name)
            assertTrue(src.contains("CarArtPainter("), "$name phải vẽ hình xe qua CarArtPainter (nguồn CarArtSource), không tự dựng")
            assertFalse(src.contains("drawRoundRect(body"), "$name vẫn vẽ thân xe bằng chữ nhật bo góc — chiếc xe THỨ HAI")
            assertFalse(src.contains("drawLine("), "$name vẫn vẽ vạch kính bằng `drawLine`")
        }
        assertFalse(boardCode("CarMiniView.kt").contains("drawRoundRect("), "CarMiniView là chiếc xe thứ ba (hệ 150×250) — AC1.4 cấm")
        // Tầng vẽ KHÔNG gọi thẳng CarFrames để lấy hình (AC1.6) — chỉ tra tên mảnh/bánh (`pieceIdOf`/`wheelIdOf`).
        boardFiles.forEach { name ->
            val direct = Regex("""CarFrames\.(path|bounds|frameBounds|openFrameBounds|pieces|fit)\(""").findAll(boardCode(name)).map { it.value }.toList()
            assertEquals(emptyList<String>(), direct, "$name gọi thẳng hình học của CarFrames — phải đi qua CarArtSource/CarArtPainter")
        }
    }

    /** Chuỗi path chỉ được sống ở TỆP SINH; `CarFrames.kt` và mọi tệp khác 0 literal. */
    @Test
    fun `chi CarFramesGenerated duoc giu chuoi path`() {
        Files.list(SourceRoots.path("src/main/java/com/byd/clusternav/launcher")).use { stream ->
            stream.map { it.fileName.toString() }.filter { it.endsWith(".kt") && it != "CarFramesGenerated.kt" }.toList()
        }.forEach { name ->
            val found = LITERAL.findAll(boardCode(name)).map { it.value }.toList()
            assertTrue(found.isEmpty(), "$name giữ chuỗi path riêng $found — nguồn hình xe phải là CarFramesGenerated (sinh)")
        }
        assertTrue(SourceRoots.text("src/main/java/com/byd/clusternav/launcher/CarFramesGenerated.kt").contains("SINH BỞI `scripts/design/gen-car.py`"), "CarFramesGenerated phải mang header sinh")
    }

    // ── 2 · chuỗi path khớp NGUYÊN VĂN với drawable, hai chiều ─────────────────────────────────────────────

    @Test
    fun `moi chuoi path sinh deu co that trong bo icon hoac mat 48dp`() {
        val inIcons = (carFiles("ic_car_") + carFiles("car_face_")).flatMap(::pathData)
            .flatMap { d -> listOf(d) + d.split(" M").mapIndexed { i, s -> if (i == 0) s else "M$s" } }
            .toSet()
        val pieces = Regex("""Piece\("(\w+)", "(\w+)", "(\w+)", "(\w+)", "(M[^"]*)"""").findAll(generated)
            .map { it.groupValues }.toList()
        assertTrue(pieces.size >= EXPECTED_PATHS, "CarFramesGenerated phải khai ít nhất $EXPECTED_PATHS mảnh (thấy ${pieces.size})")
        // Mảnh MANG DỮ LIỆU (thân · kính · bánh · cửa) phải có mặt trong một drawable — đó là "một nguồn hai đích".
        // Lớp trạng thái (đèn/xi-nhan chỉ sáng khi bật) và trang trí (quầng, bóng, ký hiệu) chỉ Canvas dùng: không bắt.
        val dataLayers = setOf("body", "glass", "tyres", "doors")
        pieces.filter { it[3] in dataLayers }.forEach { g ->
            val d = g[5]
            assertTrue(inIcons.any { it == d || it.contains(d) }, "mảnh ${g[1]}/${g[2]} KHÔNG có trong tệp ic_car_*/car_face_* nào ⇒ hình trôi khỏi bộ icon: $d")
        }
    }

    /**
     * Chiều ngược: mọi `android:pathData` của MỌI `ic_car_*` là một mảnh hoặc chuỗi NỐI các mảnh (bằng một dấu
     * cách, theo thứ tự) — không icon nào mang path "ngoài nguồn". Riêng bốn icon lốp phải đúng 3 path (thân · kính · bánh).
     */
    @Test
    fun `moi path cua icon xe deu ghep tu manh sinh`() {
        val pieces = generatedPaths().toSet()
        carFiles("ic_car_").forEach { file ->
            pathData(file).forEach { d ->
                assertTrue(coveredByPieces(d, pieces), "$file có path không ghép từ mảnh sinh: $d")
            }
        }
        TyreCorner.values().forEach { corner ->
            val file = "ic_car_top_tyre_${SUFFIX.getValue(corner)}.xml"
            assertEquals(3, pathData(file).size, "$file phải là thân + kính + bánh (3 path)")
        }
    }

    private fun coveredByPieces(d: String, pieces: Set<String>): Boolean {
        if (d in pieces) return true
        var rest = d
        while (rest.isNotEmpty()) {
            val next = pieces.filter { rest.startsWith(it) }.maxByOrNull { it.length } ?: return false
            rest = rest.removePrefix(next).trimStart()
        }
        return true
    }

    /** AC1.1 — đúng ba tệp SVG nguồn; mỗi mặt trong `CarFramesGenerated` có mảnh, và tên mặt khớp enum `CarFace`. */
    @Test
    fun `dung ba tep SVG nguon va ba mat sinh`() {
        val svgs = Files.list(SourceRoots.path("../design/car")).use { s -> s.map { it.fileName.toString() }.filter { it.endsWith(".svg") }.toList().sorted() }
        assertEquals(listOf("front.svg", "side.svg", "top.svg"), svgs)
        CarFace.values().forEach { f ->
            assertTrue(generated.contains("Piece(\"${f.name.lowercase()}\", "), "CarFramesGenerated không có mảnh nào của mặt $f")
        }
    }

    // ── 3 · phóng giữ tỉ lệ, và chỉ một chỗ dựng ma trận ───────────────────────────────────────────────────

    @Test
    fun `phong hinh xe GIU TI LE, khong keo gian`() {
        assertTrue(frames.contains("Matrix.ScaleToFit.CENTER"), "phải phóng bằng ScaleToFit.CENTER — kéo giãn là làm ra chiếc xe thứ hai (R1)")
        listOf("ScaleToFit.FILL", "ScaleToFit.START", "ScaleToFit.END").forEach { assertFalse(frames.contains(it), "$it không giữ tỉ lệ") }
        (boardFiles + "CarArtPainter.kt").forEach { name ->
            assertFalse(boardCode(name).contains("setRectToRect("), "$name tự dựng ma trận phóng — phải đi qua CarFrames.fit")
        }
    }

    @Test
    fun `net khung xe co SAN lay tu thang khoang cach`() {
        boardFiles.forEach { name ->
            val src = boardCode(name)
            assertTrue(src.contains("strokeFloorPx"), "$name phải có sàn nét khung xe")
            assertTrue(src.contains("Sp.STROKE"), "$name phải lấy sàn từ KachiSpace, không đẻ số riêng")
        }
    }

    /** Không cấp phát trong `onDraw`/`draw`/`drawPart` — nhịp trạng thái xe 1 Hz (AC5.3: shader dựng ở `layout`). */
    @Test
    fun `khong cap phat Matrix Path RectF Shader trong onDraw`() {
        val hot = boardFiles.map { it to SourceRoots.body(boardCode(it), "override fun onDraw") } +
            listOf("CarArtPainter.kt:draw" to SourceRoots.body(boardCode("CarArtPainter.kt"), "fun draw("),
                "CarArtPainter.kt:drawById" to SourceRoots.body(boardCode("CarArtPainter.kt"), "private fun drawById"))
        hot.forEach { (name, draw) ->
            listOf("Matrix", "Path", "RectF", "LinearGradient", "RadialGradient", "Paint").forEach { type ->
                assertFalse(Regex("""(?<![A-Za-z0-9_.])$type\(""").containsMatchIn(draw), "$name cấp phát `$type(` trong đường vẽ nóng")
            }
        }
    }

    /** Painter chép path sang bản riêng trước khi biến hình — không `transform` thẳng vào path dùng chung. */
    @Test
    fun `painter chep path truoc khi bien hinh`() {
        val painter = boardCode("CarArtPainter.kt")
        assertTrue(painter.contains("path.set(shape)"), "CarArtPainter phải chép sang path riêng trước khi transform")
        (boardFiles + "CarArtPainter.kt").forEach { name ->
            assertFalse(Regex("""(CarFrames|VectorCarArt|src)\.\w+(\([^)]*\))?\.transform\(""").containsMatchIn(boardCode(name)), "$name biến hình THẲNG vào path dùng chung")
        }
    }

    // ── 4 · bộ phận `:core` đủ hình · vai SVG đủ enum · mọi thành viên có chỗ gọi ──────────────────────────

    @Test
    fun `moi bo phan cua core deu co hinh trong CarFrames`() {
        val core = code("src/main/java/com/byd/clusternav/launcher/GroupBoardModel.kt")
        val body = SourceRoots.body(core, "enum class CarPart")
        val parts = Regex("""\b([A-Z][A-Z_0-9]{2,})\b""").findAll(body).map { it.groupValues[1] }.toSet()
        assertTrue(parts.size >= EXPECTED_PARTS, "đọc hụt enum CarPart (thấy $parts)")
        val ids = Regex("""CarPart\.(\w+) to "(\w+)"""").findAll(frames).associate { it.groupValues[1] to it.groupValues[2] }
        parts.forEach { p ->
            val id = ids[p]
            assertTrue(id != null, "CarFrames thiếu ánh xạ bộ phận $p ⇒ bảng bỏ qua nó, im lặng")
            assertTrue(generated.contains("Piece(\"top\", \"$id\","), "bộ phận $p trỏ mảnh '$id' không có trên mặt TRÊN")
        }
        TyreCorner.values().forEach { c -> assertTrue(frames.contains("TyreCorner.${c.name} to \"wheel_"), "CarFrames thiếu bánh ${c.name}") }
    }

    /** Mọi `role` trong tệp sinh phải là một [CarPartRole] của `:core` — vai lạ không được "tự nhiên tô được". */
    @Test
    fun `moi vai trong tep sinh deu la mot CarPartRole`() {
        val roles = Regex("""Piece\("\w+", "\w+", "\w+", "(\w+)",""").findAll(generated).map { it.groupValues[1] }.toSet()
        assertTrue(roles.size >= 10, "đọc hụt vai (thấy $roles)")
        assertEquals(emptyList<String>(), roles.filter { CarPartRole.of(it) == null }, "vai SVG không có trong CarPartRole")
    }

    /** ⚠⚠ Mọi thành viên công khai của `CarFrames` và `CarFramesGenerated` phải có ÍT NHẤT một chỗ gọi — CLAUDE.md §8. */
    @Test
    fun `moi thanh vien cong khai cua CarFrames deu co cho goi`() {
        val callers = Files.list(SourceRoots.path("src/main/java/com/byd/clusternav/launcher")).use { stream ->
            stream.map { it.fileName.toString() }.filter { it.endsWith(".kt") && it != "CarFrames.kt" && it != "CarFramesGenerated.kt" }.toList()
        }.joinToString("\n") { boardCode(it) }
        val api = Regex("""\n    (?:fun|val|const val) (\w+)""").findAll(frames).map { it.groupValues[1] }.toSet()
        assertTrue(api.size >= EXPECTED_API, "đọc hụt API của CarFrames (thấy $api)")
        api.forEach { assertTrue(callers.contains("CarFrames.$it"), "CarFrames.$it không có chỗ gọi nào ⇒ hình trôi mà không ai thấy") }
        val gen = Regex("""\n    (?:fun|val|const val) (\w+)""").findAll(generated).map { it.groupValues[1] }.toSet()
        assertTrue(gen.isNotEmpty())
        gen.forEach { assertTrue(callers.contains("CarFramesGenerated.$it") || frames.contains("CarFramesGenerated.$it"), "CarFramesGenerated.$it không ai gọi") }
        assertFalse(generated.contains("const val"), "tệp sinh không được có const val (KachiTheme.kt:11-15)")
    }

    private companion object {
        val PATH_DATA = Regex("""android:pathData="([^"]+)"""")

        /** Chuỗi path SVG viết trong mã Kotlin: nháy kép, bắt đầu bằng lệnh `M`. */
        val LITERAL = Regex(""""(M[0-9][^"]*)"""")

        /** Ba mặt: TOP 27 khung + 14 glyph · FRONT 19 + 8 · SIDE 18 (B2 2026-09-17) ⇒ ≥ 80. */
        const val EXPECTED_PATHS = 80
        const val EXPECTED_PARTS = 8

        /** `pieceIdOf` · `wheelIdOf` · `pieces` · `path` · `bounds` · `frameBounds` · `openFrameBounds` · `fit` · `BODY`. */
        const val EXPECTED_API = 9

        val SUFFIX: Map<TyreCorner, String> = mapOf(
            TyreCorner.FRONT_LEFT to "fl", TyreCorner.FRONT_RIGHT to "fr", TyreCorner.REAR_LEFT to "rl", TyreCorner.REAR_RIGHT to "rr",
        )
    }
}
